require("nvim-treesitter").setup {
    ensure_installed = {
        "bash",
        "c",
        "cmake",
        "cpp",
        "fish",
        "javascript",
        "lua",
        "luadoc",
        "make",
        "markdown",
        "printf",
        "python",
        "svelte",
        "toml",
        "typescript",
        "vim",
        "vimdoc",
        "yaml",
    },
}
